import type { Book } from "./types"

export const mockBooks: Book[] = [
  {
    id: "1",
    title: "Cien años de soledad",
    author: "Gabriel García Márquez",
    genre: "ficción",
    coverImage: "/cien-a-os-de-soledad-book-cover.jpg",
    description:
      "Una obra maestra del realismo mágico que narra la historia de la familia Buendía a lo largo de siete generaciones en el pueblo ficticio de Macondo. Una exploración profunda de la soledad, el amor, y el destino.",
    publishedYear: 1967,
    pages: 417,
    isbn: "978-0307474728",
    rating: 4.8,
    reviews: [
      {
        id: "r1",
        author: "María González",
        rating: 5,
        comment: "Una obra maestra absoluta. La prosa de García Márquez es simplemente hipnotizante.",
        date: "2024-01-15",
      },
      {
        id: "r2",
        author: "Carlos Ruiz",
        rating: 5,
        comment: "Cada vez que lo leo descubro algo nuevo. Imprescindible en cualquier biblioteca.",
        date: "2024-02-20",
      },
    ],
  },
  {
    id: "2",
    title: "La sombra del viento",
    author: "Carlos Ruiz Zafón",
    genre: "misterio",
    coverImage: "/la-sombra-del-viento-book-cover.jpg",
    description:
      "En la Barcelona de posguerra, un joven descubre un libro misterioso que cambiará su vida para siempre. Una historia de amor, misterio y libros que te atrapará desde la primera página.",
    publishedYear: 2001,
    pages: 565,
    isbn: "978-0143034902",
    rating: 4.7,
    reviews: [
      {
        id: "r3",
        author: "Ana Martínez",
        rating: 5,
        comment: "Una historia fascinante que te transporta a la Barcelona de otra época. No pude soltarlo.",
        date: "2024-01-10",
      },
      {
        id: "r4",
        author: "Pedro Sánchez",
        rating: 4,
        comment: "Excelente narrativa y personajes muy bien desarrollados. Altamente recomendado.",
        date: "2024-03-05",
      },
    ],
  },
  {
    id: "3",
    title: "Rayuela",
    author: "Julio Cortázar",
    genre: "ficción",
    coverImage: "/rayuela-cortazar-book-cover.jpg",
    description:
      "Una novela experimental que puede leerse de múltiples formas. Sigue las aventuras de Horacio Oliveira en París y Buenos Aires en una búsqueda existencial única.",
    publishedYear: 1963,
    pages: 600,
    isbn: "978-8420471648",
    rating: 4.5,
    reviews: [
      {
        id: "r5",
        author: "Laura Fernández",
        rating: 5,
        comment: "Una experiencia de lectura única. Cortázar rompe todos los moldes.",
        date: "2024-02-14",
      },
    ],
  },
  {
    id: "4",
    title: "El amor en los tiempos del cólera",
    author: "Gabriel García Márquez",
    genre: "romance",
    coverImage: "/el-amor-en-los-tiempos-del-colera-book-cover.jpg",
    description:
      "Una historia de amor que trasciende el tiempo. Florentino Ariza espera más de cincuenta años para declarar su amor a Fermina Daza. Una obra conmovedora sobre la persistencia del amor.",
    publishedYear: 1985,
    pages: 368,
    isbn: "978-0307389732",
    rating: 4.6,
    reviews: [
      {
        id: "r6",
        author: "Roberto Díaz",
        rating: 5,
        comment: "La historia de amor más hermosa que he leído. García Márquez en su máximo esplendor.",
        date: "2024-01-25",
      },
      {
        id: "r7",
        author: "Isabel Torres",
        rating: 4,
        comment: "Emotiva y bellamente escrita. Un clásico que todos deberían leer.",
        date: "2024-03-12",
      },
    ],
  },
  {
    id: "5",
    title: "Ficciones",
    author: "Jorge Luis Borges",
    genre: "ficción",
    coverImage: "/ficciones-borges-book-cover.jpg",
    description:
      "Una colección de cuentos que desafían la realidad y exploran laberintos metafísicos. Borges crea universos paralelos y bibliotecas infinitas en estas obras maestras del cuento corto.",
    publishedYear: 1944,
    pages: 174,
    isbn: "978-0802130303",
    rating: 4.7,
    reviews: [
      {
        id: "r8",
        author: "Miguel Ángel",
        rating: 5,
        comment: "Borges es un genio. Cada cuento es una joya literaria que te hace pensar.",
        date: "2024-02-08",
      },
    ],
  },
  {
    id: "6",
    title: "La casa de los espíritus",
    author: "Isabel Allende",
    genre: "ficción",
    coverImage: "/la-casa-de-los-espiritus-book-cover.jpg",
    description:
      "La saga de la familia Trueba a través de cuatro generaciones. Una mezcla de realismo mágico, política y amor que retrata la historia de Chile de manera inolvidable.",
    publishedYear: 1982,
    pages: 433,
    isbn: "978-1501117015",
    rating: 4.6,
    reviews: [
      {
        id: "r9",
        author: "Carmen López",
        rating: 5,
        comment: "Una saga familiar fascinante. Allende teje una historia mágica y conmovedora.",
        date: "2024-01-30",
      },
      {
        id: "r10",
        author: "Javier Moreno",
        rating: 4,
        comment: "Excelente novela que combina historia y fantasía de manera magistral.",
        date: "2024-03-18",
      },
    ],
  },
  {
    id: "7",
    title: "El túnel",
    author: "Ernesto Sabato",
    genre: "thriller",
    coverImage: "/el-tunel-sabato-book-cover.jpg",
    description:
      "Una novela psicológica intensa sobre la obsesión y la locura. Juan Pablo Castel, un pintor atormentado, narra su historia de amor y crimen en primera persona.",
    publishedYear: 1948,
    pages: 158,
    isbn: "978-0345803429",
    rating: 4.4,
    reviews: [
      {
        id: "r11",
        author: "Sofía Ramírez",
        rating: 4,
        comment: "Inquietante y profunda. Una exploración magistral de la mente humana.",
        date: "2024-02-22",
      },
    ],
  },
  {
    id: "8",
    title: "Crónica de una muerte anunciada",
    author: "Gabriel García Márquez",
    genre: "misterio",
    coverImage: "/cronica-de-una-muerte-anunciada-book-cover.jpg",
    description:
      "Todos sabían que iban a matar a Santiago Nasar. Una crónica magistral sobre el honor, la fatalidad y la culpa colectiva en un pequeño pueblo colombiano.",
    publishedYear: 1981,
    pages: 120,
    isbn: "978-1400034710",
    rating: 4.5,
    reviews: [
      {
        id: "r12",
        author: "Diego Herrera",
        rating: 5,
        comment: "Corta pero impactante. García Márquez en estado puro.",
        date: "2024-03-01",
      },
    ],
  },
  {
    id: "9",
    title: "Los detectives salvajes",
    author: "Roberto Bolaño",
    genre: "ficción",
    coverImage: "/los-detectives-salvajes-book-cover.jpg",
    description:
      "Una novela ambiciosa que sigue a un grupo de poetas en México y su búsqueda de una poeta desaparecida. Una obra maestra de la literatura latinoamericana contemporánea.",
    publishedYear: 1998,
    pages: 609,
    isbn: "978-0312427481",
    rating: 4.6,
    reviews: [
      {
        id: "r13",
        author: "Valentina Cruz",
        rating: 5,
        comment: "Una novela monumental. Bolaño crea un universo literario fascinante.",
        date: "2024-01-20",
      },
      {
        id: "r14",
        author: "Andrés Vargas",
        rating: 4,
        comment: "Compleja pero gratificante. Una lectura que vale la pena el esfuerzo.",
        date: "2024-02-28",
      },
    ],
  },
  {
    id: "10",
    title: "Pedro Páramo",
    author: "Juan Rulfo",
    genre: "fantasía",
    coverImage: "/pedro-paramo-book-cover.jpg",
    description:
      "Juan Preciado viaja a Comala para buscar a su padre, Pedro Páramo, solo para descubrir un pueblo habitado por fantasmas. Una obra maestra del realismo mágico mexicano.",
    publishedYear: 1955,
    pages: 124,
    isbn: "978-0802133908",
    rating: 4.7,
    reviews: [
      {
        id: "r15",
        author: "Lucía Mendoza",
        rating: 5,
        comment: "Una joya de la literatura mexicana. Atmosférica y poética.",
        date: "2024-03-10",
      },
    ],
  },
  {
    id: "11",
    title: "El laberinto de la soledad",
    author: "Octavio Paz",
    genre: "no-ficción",
    coverImage: "/el-laberinto-de-la-soledad-book-cover.jpg",
    description:
      "Un ensayo profundo sobre la identidad mexicana y la condición humana. Paz explora la psicología del mexicano y los mitos que definen su cultura.",
    publishedYear: 1950,
    pages: 398,
    isbn: "978-0140188424",
    rating: 4.5,
    reviews: [
      {
        id: "r16",
        author: "Fernando Ortiz",
        rating: 5,
        comment: "Un análisis brillante de la identidad mexicana. Lectura obligatoria.",
        date: "2024-02-05",
      },
    ],
  },
  {
    id: "12",
    title: "Veinte poemas de amor y una canción desesperada",
    author: "Pablo Neruda",
    genre: "poesía",
    coverImage: "/veinte-poemas-de-amor-neruda-book-cover.jpg",
    description:
      "Una colección icónica de poemas de amor que capturan la pasión, el deseo y la melancolía. La obra más popular de Neruda y uno de los libros de poesía más vendidos de todos los tiempos.",
    publishedYear: 1924,
    pages: 136,
    isbn: "978-0143039471",
    rating: 4.8,
    reviews: [
      {
        id: "r17",
        author: "Gabriela Rojas",
        rating: 5,
        comment: "Poesía pura y hermosa. Neruda expresa el amor como nadie más.",
        date: "2024-01-18",
      },
      {
        id: "r18",
        author: "Ricardo Paz",
        rating: 5,
        comment: "Cada poema es una obra de arte. Simplemente perfecto.",
        date: "2024-03-15",
      },
    ],
  },
]

export const genres: { value: string; label: string }[] = [
  { value: "todos", label: "Todos los géneros" },
  { value: "ficción", label: "Ficción" },
  { value: "no-ficción", label: "No ficción" },
  { value: "misterio", label: "Misterio" },
  { value: "romance", label: "Romance" },
  { value: "ciencia-ficción", label: "Ciencia ficción" },
  { value: "fantasía", label: "Fantasía" },
  { value: "biografía", label: "Biografía" },
  { value: "historia", label: "Historia" },
  { value: "poesía", label: "Poesía" },
  { value: "thriller", label: "Thriller" },
]
